/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppDatePicker: typeof import('./src/components/AppDatePicker.vue')['default']
    AppMainTable: typeof import('./src/components/AppMainTable.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BEditableTable: typeof import('bootstrap-vue-next')['BEditableTable']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
